#!/usr/bin/env bash
# duplicate web-01 to web-02
# these scripts are an upgrade from the web-server scripts...

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Uncomment to see the script run in action
#set -x

# Colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and doing some minor checks...${reset}\n"

function install() {
	command -v "$1" &> /dev/null

	if [ $? -ne 0 ]; then
		echo -e "    Installing: ${brown}$1${reset}\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq || { echo "Installation of $1 failed"; exit 1; }
		echo -e "\n"
	else
		echo -e "    ${green}${1} is already installed.${reset}\n"
	fi
}

install nginx # Install nginx

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
else
	sudo mkdir -p /var/www
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
fi

# Create directories if not present
for dir in /var/www/{html,error}; do
	if ! [ -d "$dir" ]; then
		mkdir -p "$dir"
	fi
done

# Create new index
echo "Hello World!" > /var/www/html/index.html

# Create new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup default server config file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

# Simplified server configuration
server_config="\
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name your_server_name; # Set the appropriate server name
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://th3-gr00t.tk/ permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}"

#shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

# Restart or start Nginx
if pgrep -x "nginx" > /dev/null
then
    sudo service nginx restart
else
    sudo service nginx start
fi
